name: Scheduled License Update

on:
  schedule:
    # Run daily at 1:00 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-licenses:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create config file with secrets
        run: |
          echo "import { initializeApp } from 'firebase/app';
          import { getDatabase } from 'firebase/database';

          const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            databaseURL: '${{ secrets.FIREBASE_DATABASE_URL }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}'
          };

          const app = initializeApp(firebaseConfig);
          const database = getDatabase(app);

          export { app, database };" > src/firebase.ts
          
      - name: Run license update
        run: |
          node -e "
          require('@babel/register')({
            presets: ['@babel/preset-env', '@babel/preset-typescript'],
            extensions: ['.ts', '.tsx', '.js', '.jsx']
          });
          require('./src/utils/scheduledTasks.ts').runLicenseUpdate().then(() => {
            console.log('License update completed');
            process.exit(0);
          }).catch(err => {
            console.error('License update failed:', err);
            process.exit(1);
          });
          "
        env:
          SURELC_USERNAME: jonathan.kaiser@luminarylife.com
          SURELC_PASSWORD: uav@e$f!#9K6S8L 